# Tmux Global settings(?)
set -g history-file ~/.bash_history
set -g history-limit 4096
  # No timeout after click Escape key(which means no delay?)
set -g escape-time 0
  # Start as non-login shell
set -g default-command "${SHELL}"
  # Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
  # Vi copypaste mode
set-option -g prefix C-a
set-window-option -g mode-keys vi
set -g default-terminal "screen-256color"
  # Tmux status bar
  # Docs: https://github.com/tmux/tmux/wiki/Getting-Started#formats
set -g status on
set-option -g status-position top
set-option -g renumber-windows on
set-option -g repeat-time 0
# Removes ESC delay
set -sg escape-time 0
set -g status-keys vi
set -g status-left " [#{session_name}]"
set -g status-left-length 10
set -g status-justify centre
set -g status-position top
set -g status-right "%y-%m-%d %H:%M [#{user}] "
set -g status-right-length 140
set -g status-style fg=green
set -g window-status-current-style bright,reverse
# Disable mouse
#set -g mouse off
# Enable mouse
set -g mouse on
  # Tmux pane bar
#set -g pane-border-status top
#set -g pane-border-format "[#P]-[#{pane_current_command}]-[#{pane_current_path}]"

# Tmux key bindings
  # hjkl pane traversal
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
  # HJKL pane resize
bind H resize-pane -L 2
bind J resize-pane -D 2
bind K resize-pane -U 5
bind L resize-pane -R 5
  # Recent window/session
bind b last-window
bind B switch-client -l
  # others
bind c command-prompt -p "new window name: " "new-window -n '%%'"
bind v command-prompt -p "move current window to session: " "move-window -t '%%'"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Tmux plugins | https://github.com/tmux-plugins
  # List of plugins
set -g @tpm_plugins 'tmux-plugins/tpm'
set -g @tpm_plugins 'tmux-plugins/tmux-sensible'
set -g @tpm_plugins 'tmux-plugins/tmux-sessionist'
set -g @tpm_plugins 'tmux-plugins/tmux-resurrect'
  # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run -b '~/.tmux/plugins/tpm/tpm'
