# Custom color scheme - Dark
foreground=#D0D0D0
background=#272A34
cursor=#606060
# Black
color0=#1D1F21
color8=#969896
# Red
color1=#FF4343
color9=#FF8080
# Green
color2=#51DDAA
color10=#71FFCC
# Yellow
color3=#FF9E80
color11=#FFCC80
# Blue
color4=#766AFF
color12=#B2ABFF
# Magenta
color5=#BE25BE
color13=#FE7DFE
# Cyan
color6=#31C8FF
color14=#80F0FF
# White
color7=#DDDDDD
color15=#FFFFFF
