# Custom color scheme - Light
foreground=#373B41
background=#FFFFFf
cursor=#C0C0C0
# Black
color0=#1D1F21
color8=#969896
# Red
color1=#FF4343
color9=#FF8080
# Green
color2=#51FF51
color10=#88FF88
# Yellow
color3=#FF8800
color11=#FFAA00
# Blue
color4=#766AFF
color12=#B2ABFF
# Magenta
color5=#BE25BE
color13=#FE7DFE
# Cyan
color6=#31C8FF
color14=#80F0FF
# White
color7=#DDDDDd
color15=#FFFFFF
