extra-keys = [                                   \
  [                                              \
    { key: ESC,     popup: DRAWER },             \
    { key: LEFT,    popup: HOME },               \
    { key: DOWN,    popup: PGDN },               \
    { key: CTRL,    popup: { macro: "CTRL 1" }}, \
    { key: TAB,     popup: KEYBOARD },           \
    { key: ALT,     popup: { macro: "CTRL 2" }}, \
    { key: UP,      popup: PGUP },               \
    { key: RIGHT,   popup: END },                \
    'DEL'                                        \
  ]                                              \
]
bell-character=ignore
use-black-ui=true
volume-keys=volume
allow-external-apps=true
terminal-margin-horizontal=0
terminal-margin-vertical=0
shortcut.previous-session=ctrl + 1
shortcut.next-session=ctrl + 2
