console-log-level=error
log=${HOME}/.cache/aria2.log
log-level=error

# Download
dir=${HOME}/Downloads/Aria2
continue=true
#on-download-complete=${HOME}/.config/aria2/clean.sh
on-download-stop=${HOME}/.config/aria2/clean.sh
disk-cache=64M
max-concurrent-downloads=5
max-connection-per-server=16
split=16
min-split-size=1M
timeout=60
bt-request-timeout=60
check-integrity=true
file-allocation=falloc

# Session
save-session=${HOME}/.cache/aria2.session
force-save=true
#save-session-interval=60
input-file=${HOME}/.cache/aria2.session

# Rpc
rpc-listen-all=true
rpc-secret=R@Nd0mRpCsEcR3T
# tr -dc 'A-Za-z0-9' < /dev/urandom | head -c 16; echo ""

# Http
use-head=true
header=Accept: */*
header=Accept-Language: en-US,en;q=0.9
header=Accept-Encoding: gzip, deflate, br, zstd
header=Connection: keep-alive
header=Sec-Fetch-Site: same-origin
header=Sec-Fetch-Mode: cors
header=Sec-Fetch-User: ?1
header=Sec-Fetch-Dest: empty
header=TE: trailers
save-cookies=${HOME}/.cache/cookies.txt
load-cookies=${HOME}/.cache/cookies.txt
user-agent=Mozilla/5.0 (Linux; Android 16) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/149.0.0.0 Mobile Safari/537.36

all-proxy=
http-proxy=localhost:7890
https-proxy=localhost:7890

# Bittorrent
bt-max-peers=500
max-overall-upload-limit=1M
peer-id-prefix=-qB5140-
peer-agent=qBittorrent/5.1.4
enable-dht=true
enable-dht6=true
enable-peer-exchange=true
bt-enable-lpd=true
listen-port=20501-20599
dht-listen-port=20501-20599
rpc-save-upload-metadata=false
seed-ratio=2
seed-time=1440
bt-tracker=udp://zer0day.ch:1337/announce,udp://tracker.publictracker.xyz:6969/announce,udp://tracker.opentrackr.org:1337/announce,udp://open.demonii.com:1337/announce,udp://open.stealth.si:80/announce,udp://tracker.torrent.eu.org:451/announce,udp://tracker.qu.ax:6969/announce,udp://tracker.auctor.tv:6969/announce,udp://tracker-udp.gbitt.info:80/announce,udp://torrentclub.online:54123/announce,udp://torrentclub.online:1984/announce,udp://t.overflow.biz:6969/announce,udp://retracker01-msk-virt.corbina.net:80/announce,udp://ipv4announce.sktorrent.eu:6969/announce,udp://explodie.org:6969/announce,udp://exodus.desync.com:6969/announce,udp://edgev.duckdns.org:6969/announce,https://tracker.zhuqiy.com:443/announce,https://tracker.pmman.tech:443/announce,https://tracker.nekomi.cn:443/announce,
