#!/usr/bin/sh
if [ -e /usr/share/blesh/ble.sh ]; then
  [[ $- == *i* ]] && source /usr/share/blesh/ble.sh
elif [ -e "$(find $HOME -type f -name ble.sh)" ] && [[ $BASH = *termux* ]]; then
  LC_CTYPE=C.UTF-8
  [[ $- == *i* ]] && source "$(find $HOME -type f -name ble.sh)"
elif [ -e "$(find $HOME -type f -name ble.sh)" ]; then
  [[ $- == *i* ]] && source "$(find $HOME -type f -name ble.sh)"
fi
