#!/usr/bin/sh
 # pacman
[ -z "$(command -v pacman)" ] && return

alias pacman='pacman --color=auto'
alias sP='sudo -E pacman --color=auto'
alias Ps='sudo -E pacman -S'
alias Sc='sudo -E pacman -Sc'
alias Sg='pacman -Sg'
alias Sgq='pacman -Sgq'
alias Si='pacman -Si'
alias Sl='pacman -Sl'
alias Slq='pacman -Slq'
alias Ss='pacman -Ss'
alias Ssq='pacman -Ssq'
alias Sy='sudo -E pacman -Sy'
alias Syu='sudo -E pacman -Syu'
alias Pf='pacman -F'
alias Fq='pacman -Fq'
alias Fl='pacman -Fl'
alias Fx='pacman -Fx'
alias Pq='pacman -Q'
alias Qq='pacman -Qq'
alias Qc='pacman -Qc'
alias Qg='pacman -Qg'
alias Qgq='pacman -Qgq'
alias Qs='pacman -Qs'
alias Qsq='pacman -Qsq'
alias Qi='pacman -Qi'
alias Ql='pacman -Ql'
alias Qlq='pacman -Qlq'
alias Qo='pacman -Qo'
alias Qoq='pacman -Qoq'
alias Qtdq='pacman -Qtdq'
alias Qte='pacman -Qte'
alias Qteq='pacman -Qteq'
alias Pr='sudo -E pacman -R'
alias Rc='sudo -E pacman -Rc'
alias Rnus='sudo -E pacman -Rnus'
alias cP='pacman -Q | wc -l'
oQ () {
  list_binaries () {
    echo -e "\e[1m"
    echo $1
    echo -e "\e[1;32m"
    pacman -Qlq $1                       \
    | grep /usr/bin/.                    \
    | awk '{gsub("/", " "); print $NF}'  \
    | column
    echo -e "\e[0m"
  }

  for i in $@; do
    if [ -n "$(command -v $i)" ]; then
      list_binaries $(pacman -Qoq $i)
    else
      list_binaries $i
    fi
  done

unset list_binaries
}
if [ -n "$(command -v pactree)" ]; then
   Pd  () {
     if [ -n "$2" ]; then
        local _depth="$2"
     else
        local _depth=1
     fi
     pactree -d "$_depth" "$1"
   }
   Pdr () {
     if [ -n "$2" ]; then
        local _depth="$2"
     else
        local _depth=1
     fi
     pactree -r -d "$_depth" "$1"
   }
fi
