#!/usr/bin/sh
 # pip
[ -z "$(command -v pip)" ] && return

alias Pi='pip install --user'
alias Pu='pip uninstall'
alias Pc='pip freeze | wc -l'

Pug () {
  local upgrade='pip install --user --upgrade'
  if [ -n "$(command -v pipdeptree)" ]; then
    $upgrade $(pipdeptree | grep -Eo '^[A-Za-z0-9-]+')
  else
    $upgrade $(pip freeze | grep -Eo '^[A-Za-z0-9-]+')
    pip check > /dev/null
    if [ $? -eq 1 ]; then
      $upgrade $(pip check | awk '{print $1}')
    fi
  fi
}

# pip completion --bash
_pip_completion() {
  COMPREPLY=( $( COMP_WORDS="${COMP_WORDS[*]}"      \
                 COMP_CWORD=$COMP_CWORD             \
                 PIP_AUTO_COMPLETE=1 $1 2>/dev/null \
              )
  )
}
complete -o default -F _pip_completion pip
