#!/usr/bin/sh
if [[ $SHELL != *termux* ]]; then
  return
fi

Mpd() {
  Mpd_stop() {
    pkill mpd
    pkill snapserver
  }
  Mpd_start() {
    Mpd_stop
    mpd &>/dev/null
    snapserver &>/dev/null &
  }
  if [ -z "$1" ]; then
#    pulseaudio --start
#    pacmd load-module module-pipe-sink file=$PREFIX/tmp/snapfifo sink_name=Snapcast format=s16le rate=48000
#    pacmd update-sink-proplist Snapcast device.description=Snapcast
#    pacmd set-default-sink Snapcast
    Mpd_start
  elif [ "$1" = "stop" ]; then
    Mpd_stop
  else
    echo "Invalid arguments."
    echo "Usage:"
    echo "Mpd       # start"
    echo "Mpd stop  # stop"
  fi
  unset Mpd_stop
  unset Mpd_start
}
