#!/usr/bin/env bash
run='i3-msg exec'
trap 'echo fuck it ERROR OCC' ERR
pkill picom
pkill v2ray
sleep 3s
$run picom
$run cgnoproxy qv2ray
xrdb ~/.Xresources
$run blueman-tray
$run deadd-notification-center
$run xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
$run xinput float $(xinput list | grep AT | awk '{sub(".*id=", ""); print $1}')
fcitx
$run nm-applet
xmodmap ~/.xmodmaprc
