#!/usr/bin/env bash

run='i3-msg exec'

lock='i3lock-fancy -n && $temporarily_run xmodmap ~/.xmodmaprc'
$run xss-lock --transfer-sleep-lock --ignore-sleep -- $lock

# restore brightness
$run sudo xbacklight -set $(cat ~/.config/i3status/brightness | sed 's/%//')
$run xset b off

$run blueman-applet
$run mpris-proxy
$run /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
$run keynav
$run unclutter
$run fcitx5

$run localsend
$run flclash

sleep 5

i3-msg '[class=Localsend]' kill
i3-msg '[class=Com.follow.clash]' kill
#$run barrier
